AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Documentation:
    Enabled: false
